### ISSUE TITLE
Release of improved and refreshed mC4 multilingual corpus

### ISSUE THREAD

**Issue by stephanpeitz** [google-research/t5x#1262]
Hi all,

one of the contributions of [UNIMAX: FAIRER AND MORE EFFECTIVE LANGUAGE SAMPLING FOR LARGE-SCALE MULTILINGUAL PRE- TRAINING](https://arxiv.org/pdf/2304.09151.pdf) is releasing "an improved and refreshed mC4 multilingual corpus consisting of 29 trillion characters across 107 languages".

I couldn't find the corpus in this repo. Has the corpus been released yet?

Thanks for your help!

Cheers,
Stephan

PS: Great work! :)

**Comment by StephennFernandes** [comment]
you can find the newer mc4 corpus here: https://huggingface.co/datasets/allenai/c4/tree/mC4_3.1.0/multilingual

**Comment by stephanpeitz** [comment]
Thanks for the pointer, much appreciated!
