### ISSUE TITLE
FileNotFoundError when using tfds.build

### ISSUE THREAD

**Issue by zhangzx-uiuc** [google-research/t5x#1309]
Hi,

I encountered a FileNotFoundError when trying to run `tfds build wmt_t2t_translate ${TFDS_DATA_DIR}` to download and process the WMT data. The error messages are as follows:
```
 File "/home/zhangzx.sjtu/miniconda3/lib/python3.10/site-packages/tensorflow_datasets/scripts/cli/build.py", line 434, in _validate_script_path
    raise FileNotFoundError(
FileNotFoundError: Could not find dataset generation script: /home/zhangzx.sjtu/storage/data/data.py. 
```
Any ideas on why there is a script needed? Thanks!

I was using `tfds-nightly==tfds-nightly                 4.9.2.dev202306160045`

**Comment by vgaraujov** [comment]
did you solve this problem?
