### ISSUE TITLE
byT5

### ISSUE THREAD

**Issue by peregilk** [google-research/t5x#164]
I see that the byT5 model is implemented in T5x but I can not find any byT5 checkpoint to initiate finetuning from. Any chance you could make such a checkpoint available?

**Comment by adarob** [comment]
We don't have the converted checkpoints yet, but you can use the original ones for now -- conversion will happen on the fly.

FYI @nconstant-google @lintingxue .

**Comment by peregilk** [comment]
Awesome! Thanks.

**Comment by nconstant-google** [comment]
ByT5 T5X checkpoints are now released:

https://github.com/google-research/t5x/blob/main/docs/models.md#byt5-checkpoints
