### ISSUE TITLE
Out of RAM when training T5x on WMT14 En-De with Colab's TPU

### ISSUE THREAD

**Issue by LeoLaugier** [google-research/t5x#214]
Hi, 

I wanted to check if I can train and evaluate T5x Base on Colab's TPU. 

When I try it in [this Colab notebook](https://colab.research.google.com/drive/10_gua3qyK9XH1TJGLXp5UCwzKh7UmjnR?usp=sharing), the session crashes after requesting more RAM than available (12 GB).

The last information log I receive is

`trainer.py:472] Training: step 0`

And the last warning I get is:

`/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py:800: UserWarning: Some donated buffers were not usable: s32[], f32[768]{0}, f32[768]{0}, f32[768]{0}, [...]", ".join(unused_donations)))`

Do you know if this is some Jax / TPU related issue, and whether one can use Colab's TPU / GPU to train and eval T5x? 

Thank you for your time,

Leo

**Comment by LeoLaugier** [comment]
Thanks @adarob 

(FYI, I was able to fine-tune T5-3B's original TF implementation on Colab.) 

Good to know that a future Colab example may be released at some point. 

Best,

Leo

**Comment by swcrazyfan** [comment]
> Thanks @adarob 
> 
> 
> 
> (FYI, I was able to fine-tune T5-3B's original TF implementation on Colab.) 
> 
> 
> 
> Good to know that a future Colab example may be released at some point. 
> 
> 
> 
> Best,
> 
> 
> 
> Leo

Hey! Could you share your Colab notebook with me?

**Comment by LeoLaugier** [comment]
Hi, the notebook is [here](https://colab.research.google.com/drive/10_gua3qyK9XH1TJGLXp5UCwzKh7UmjnR?usp=sharing).

Let me know if you can't open it. 

Best, 

Leo

**Comment by swcrazyfan** [comment]
Thanks so much! Opened it, and I'm looking through it now. I can't find anything about what kind of data format I should put in the data directory. Is a CSV fine or should it be something like tfrecords?

**Comment by LeoLaugier** [comment]
The notebook is based on the example given by [t5x's README](https://github.com/google-research/t5x#example-english-to-german-translation) (English to German translation): the data correspond to the [_wmt_t2t_ende_v003_](https://github.com/google-research/text-to-text-transfer-transformer/blob/d81c0bab2a41b4d5dfbe4971de32f7d67df65f31/t5/data/tasks.py#L212) task.

**Comment by tai-dang11** [comment]
> Hi, the notebook is [here](https://colab.research.google.com/drive/10_gua3qyK9XH1TJGLXp5UCwzKh7UmjnR?usp=sharing).
> 
> Let me know if you can't open it.
> 
> Best,
> 
> Leo

Hi Leo, 

I tried to run your colab, but I ran into this error when I tried to run train.py

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/content/t5x/t5x/train.py](https://wxlr2tebez-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220721-060048-RC00_462350521#) in <module>()
     30 from absl import logging
     31 from clu import metric_writers
---> 32 import clu.data
     33 import jax
     34 from jax import random

2 frames
[/usr/local/lib/python3.7/dist-packages/clu/data/dataset_iterator.py](https://wxlr2tebez-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220721-060048-RC00_462350521#) in TfDatasetIterator()
    147     self._ckpt = self._tf.train.Checkpoint(ds=self.iterator)
    148 
--> 149   @functools.cached_property
    150   def element_spec(self) -> ElementSpec:
    151     element_spec = self._dataset.element_spec

AttributeError: module 'functools' has no attribute 'cached_property'

"cached_property" requires python 3.8 or higher, but the Python version on Colab is only 3.7. How did you run your train.py?

Best,
Tai

**Comment by LeoLaugier** [comment]
Hi Tai, 

It seemed to work at that time. My guess is that some package has been updated since then and broke something in the Colab notebook.

Maybe try to install an older version of T5x? (from around Feb, 2nd 2022?)
