### ISSUE TITLE
Pretraining from scratch

### ISSUE THREAD

**Issue by peregilk** [google-research/t5x#24]
Thanks a lot for releasing this code. We have been trying to train a Norwegian T5-base from the sample Flax T5 (v1.1) [implementation](https://github.com/huggingface/transformers/tree/master/examples/flax/language-modeling) by the HuggingFace team. We have however been struggling with some instabilities when finetuning this models [described in this issue](https://github.com/huggingface/transformers/issues/13335#issuecomment-909106756), and were just looking into trying another implementation. Your implementation was released at a perfect time.

Could you provide some more info about how to use this library for pretraining a T5 for another language from scratch? 

And particularly how the seqIO sentencepiece tokenizer model is implemented? Can this simply be replaced with the SentencePiece tokenizer trained by the [SentencePieceUnigramTokenizer from HuggingFace Tokenizer](https://github.com/huggingface/tokenizers).

**Comment by adarob** [comment]
We typically use seqio Tasks to set up the data pipelines with T5X.  You can see the original T5 pretraining Task here: https://github.com/google-research/text-to-text-transfer-transformer/blob/3d10afd51ba97ac29eb66ae701eca274488202f7/t5/data/tasks.py#L45

It should certainly be possible to wrap the HuggingFace tokenizer in a seqio.Vocabulary like we did for SentencePiece: https://github.com/google/seqio/blob/3c4672689f8f9aafeebb1adb9f753977dbe77f43/seqio/vocabularies.py#L186

Once you've created your new task, you should be able to follow the pretraining instructions in the README and override the `TASK_OR_MIXTURE` with your task.

**Comment by adarob** [comment]
Closing this issue, but please open a new thread in "Discussions" if you have additional questions.
