### ISSUE TITLE
How to control which layers are trainable?

### ISSUE THREAD

**Issue by lintangsutawika** [google-research/t5x#30]
What parameters should I change to control which layers or model params are trainable?

In the [mesh tf version](https://github.com/google-research/text-to-text-transfer-transformer) I can use `run.variable_filter` but is that also possible to add to the gin file here?

**Comment by blester125** [comment]
Currently you can use a MultiOptimizer to do this. We do it a lot when we use T5X for Prompt Tuning. You can find an example of doing that here https://github.com/google-research/prompt-tuning/blob/a7d507fbb01c0a5d24c9726bd61dbf966024c0d0/prompt_tuning/configs/models/t5_1_1_base_prompt.gin#L65
