### ISSUE TITLE
Convert script not running

### ISSUE THREAD

**Issue by peregilk** [google-research/t5x#370]
It is not currently possible to run the MT->T5X convertion script directly like this:

````
python -m t5x.scripts.convert_tf_checkpoint \
 --gin_file=t5x/examples/t5/t5_1_0/small.gin\
 --gin.convert_checkpoint.model=%MODEL\
 --gin.convert_checkpoint.tf_checkpoint_path=\
\"gs://t5-data/pretrained_models/small/model.ckpt-1000000\"\
 --gin.convert_checkpoint.output_dir=\"/tmp/t5x_checkpoints/t5_small\"
````
You are getting the following error:

````
 raise ValueError(fmt.format(binding_key))                                                                                                                                                    
ValueError: DROPOUT_RATE/macro.value set to `%gin.REQUIRED` but not subsequently overridden.
````

Setting DROPOUT_RATE manually, for instance at the end of the small.gin-file, is a workaround. Not sure what is a clean way of fixing the issue.

**Comment by peregilk** [comment]
Since there now is a direct conversion-script from T5X to Transformers, this is no longer an issue. Closing.

**Comment by justinphan3110** [comment]
Hi @peregilk , do you remember what is the parsing value for ```%MODEL``` ?
