### ISSUE TITLE
Using Custom Datasets

### ISSUE THREAD

**Issue by nimasadri11** [google-research/t5x#408]
I have a custom dataset that I want to use to train. To convert it to `tfds` I am using these instructions: [https://www.tensorflow.org/datasets/add_dataset](), but things don't work. Are there other instructions for generating the `tfds` that I should be following instead of the one mentioned above?

**Comment by adarob** [comment]
Hi Nima. You don't actually need to create a TFDS dataset or even a SeqIO task. However, creating a SeqIO task is the easiest way to use T5X at this time. See https://github.com/google/seqio for instructions.

**Comment by nimasadri11** [comment]
@adarob My `tfds` does not have "inputs" and "targets". My features are called something else (and I have 3 types of features in fact). How can I handle this case with t5x?

**Comment by adarob** [comment]
Yes, this can be done in the seqio preprocessors.
