### ISSUE TITLE
Dataset seeking for restarting from a crash run

### ISSUE THREAD

**Issue by versae** [google-research/t5x#421]
I wrote some hacky support for HuggingFace datasets using `seqio.FunctionDataSource`, specifically for pretraining and finetuning pretrained models.

```python
def gen_dataset(split, shuffle=False, seed=None, column="text", dataset_params=None):
    dataset = load_dataset(**dataset_params)
    if shuffle:
        if seed:
            dataset = dataset.shuffle(seed=seed)
        else:
            dataset = dataset.shuffle()
    while True:  # TODO: add for...loop over num_epochs
        for item in dataset[str(split)]:
            yield item[column]

def dataset_fn(split, shuffle_files, seed=None, dataset_params=None):
    return tf.data.Dataset.from_generator(
        functools.partial(gen_dataset, split, shuffle_files, seed, dataset_params=dataset_params),
        output_signature=tf.TensorSpec(shape=(), dtype=tf.string, name=dataset_name)
    )

dataset_name = 'NbAiLab/NCC'
dataset_params = {"path": dataset_name, "streaming": True}
dataset_shapes = {"train": 20830348, "validation": 473079}
source = seqio.FunctionDataSource(
    dataset_fn=functools.partial(dataset_fn, dataset_params=dataset_params),
    splits=("train", "validation"),
    caching_permitted=False,
    num_input_examples=dataset_shapes,
)
``` 

But unfortunately, as I face constant random crashes during training (#366), I need a way to seek to the right dataset batch to properly continue training.

I see there's a `continue_from_last_checkpoint` variable in [`get_dataset()`](https://github.com/google-research/t5x/blob/main/t5x/utils.py#L868), bit it seems is not used for anything yet.

Is there a way to pass in the needed information to `get_dataset_fn()` so I can write the logic without using any hard-coded global variables?

**Comment by adarob** [comment]
Please reopen at https://github.com/google/seqio for proper triage. 

The short answer is that someone would need to implement a specific DatasetProvider for hfds, which shouldn't be too hard.

You could also run the offline caching job to create tfrecords capable of being recovered on crash.
