### ISSUE TITLE
Provide an interactive class for mixing training and inference.

### ISSUE THREAD

**Issue by GallagherCommaJack** [google-research/t5x#537]
There's a lot of instructions here about how I could train/fine-tune t5 itself directly on natural language tasks and datasets, but I'm interested in training another model which would take t5 embeds of language as an input.

In order to do this, I would need to interleave t5 inference with my training script, which means I need a way to run t5 on a single batch not just on an entire dataset. How should I go about this?

**Comment by adarob** [comment]
@kkenealy is working on an `InteractiveModel` class that will make this easier to do along with a Colab demo.
In the meantime, you should take a look at the `Model` class interface, which provides a `predict_batch` method for inference and the `Trainer` class, which provides a `train` method that supports single-batch training.

**Comment by kkenealy** [comment]
Given an instance of the Model class, you can load a checkpoint using a CheckpointConfig; see these lines for an example: https://github.com/google-research/t5x/blob/999fccbfda10c107de7e4c071c976999621d8a79/t5x/train.py#L268

**Comment by jon-chuang** [comment]
Hello, should this be closed? Seems that UL2 can now be loaded as `InteractiveModel`: https://github.com/google-research/t5x/issues/1226
