### ISSUE TITLE
How to log in wandb ? 

### ISSUE THREAD

**Issue by StephennFernandes** [google-research/t5x#557]
Hey there, i see that tensorboard is the primary logging mechanism here. Perhaps if i wanted to log all the metrics that tensorboard is logging into wandb, how should I do that ?

**Comment by adarob** [comment]
You would just need to define a `clu.Metric.MetricWriter` for wandb. It looks like right now you'd have to then hack that into `t5x.trainer.MetricsManager` to actually use it. However, we could make it so you can pass in a different set of `MetricWriters` via gin.

**Comment by StephennFernandes** [comment]
@adarob thanks for replying. This sounds great! , however wandb has a way to absorb the tensorboard logger if it points correctly to it the runner/log file. In the T5X dir structure where would the  tensorboard file be ? also, does T5X pre-training script start logging to tensorboard by default or  do we need to set it ?
