### ISSUE TITLE
RuntimeError: UNIMPLEMENTED: Requested AllReduceStart not implemented on GPU

### ISSUE THREAD

**Issue by ibulu** [google-research/t5x#580]
I am trying to run one of the fine-tuning examples on a machine with 2 GPUs and getting the following error:

RuntimeError: UNIMPLEMENTED: Requested AllReduceStart not implemented on GPU; replica_count: 1; partition_count: 2, group_mode: kCrossReplicaAndPartition, operand_count: 49; NCCL support: 1; first operand array element-type: BF16
  In call to configurable 'train' (<function train at 0x7fed3c31e3a0>)

full error trace below:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [19], in <cell line: 24>()
     17     gin_utils.parse_gin_flags(
     18         # User-provided gin paths take precedence if relative paths conflict.
     19         FLAGS.gin_search_paths,# + _DEFAULT_GIN_SEARCH_PATHS,
     20         FLAGS.gin_file,
     21         FLAGS.gin_bindings)
     22     train_using_gin()
---> 24 gin_utils.run(main_train)

File /anaconda/envs/py39/lib/python3.9/site-packages/t5x/gin_utils.py:105, in run(main)
    103 def run(main):
    104   """Wrapper for app.run that rewrites gin args before parsing."""
--> 105   app.run(
    106       main,
    107       flags_parser=lambda a: app.parse_flags_with_usage(rewrite_gin_args(a)))

File /anaconda/envs/py39/lib/python3.9/site-packages/absl/app.py:312, in run(main, argv, flags_parser)
    310   callback()
    311 try:
--> 312   _run_main(main, args)
    313 except UsageError as error:
    314   usage(shorthelp=True, detailed_error=error, exitcode=error.exitcode)

File /anaconda/envs/py39/lib/python3.9/site-packages/absl/app.py:258, in _run_main(main, argv)
    256   sys.exit(retval)
    257 else:
--> 258   sys.exit(main(argv))

Input In [18], in main_train(argv)
      1 def main_train(argv: Sequence[str]):
      2     """Wrapper for pdb post mortems."""
----> 3     _main(argv)

Input In [19], in _main(argv)
     15 train_using_gin = gin.configurable(train)
     17 gin_utils.parse_gin_flags(
     18     # User-provided gin paths take precedence if relative paths conflict.
     19     FLAGS.gin_search_paths,# + _DEFAULT_GIN_SEARCH_PATHS,
     20     FLAGS.gin_file,
     21     FLAGS.gin_bindings)
---> 22 train_using_gin()

File /anaconda/envs/py39/lib/python3.9/site-packages/gin/config.py:1605, in _make_gin_wrapper.<locals>.gin_wrapper(*args, **kwargs)
   1603 scope_info = " in scope '{}'".format(scope_str) if scope_str else ''
   1604 err_str = err_str.format(name, fn_or_cls, scope_info)
-> 1605 utils.augment_exception_message_and_reraise(e, err_str)

File /anaconda/envs/py39/lib/python3.9/site-packages/gin/utils.py:41, in augment_exception_message_and_reraise(exception, message)
     39 proxy = ExceptionProxy()
     40 ExceptionProxy.__qualname__ = type(exception).__qualname__
---> 41 raise proxy.with_traceback(exception.__traceback__) from None

File /anaconda/envs/py39/lib/python3.9/site-packages/gin/config.py:1582, in _make_gin_wrapper.<locals>.gin_wrapper(*args, **kwargs)
   1579 new_kwargs.update(kwargs)
   1581 try:
-> 1582   return fn(*new_args, **new_kwargs)
   1583 except Exception as e:  # pylint: disable=broad-except
   1584   err_str = ''

Input In [10], in train(model, train_dataset_cfg, train_eval_dataset_cfg, infer_eval_dataset_cfg, checkpoint_cfg, partitioner, trainer_cls, model_dir, total_steps, eval_steps, eval_period, stats_period, random_seed, use_hardware_rng, summarize_config_fn, inference_evaluator_cls, get_dataset_fn, concurrent_metrics, actions, train_eval_get_dataset_fn, run_eval_before_training, use_gda)
    422 logging.info('Compiling train loop.')
    423 logging.flush()
--> 424 trainer.compile_train(first_batch)
    426 # Main Loop over "epochs".
    427 for epoch in range(first_epoch, num_epochs):

File /anaconda/envs/py39/lib/python3.9/site-packages/t5x/trainer.py:545, in BaseTrainer.compile_train(self, batch)
    532 """Pre-compiles train step (if not yet compiled).
    533 
    534 Not required.
   (...)
    542     shapes and dtypes.
    543 """
    544 tick = time.time()
--> 545 self._compiled_train_step = self._partitioner.compile(
    546     self._partitioned_train_step, self.train_state, batch)
    547 tock = time.time()
    548 self.train_metrics_manager.write_scalar("timing/compilation_seconds",
    549                                         tock - tick, self.train_state.step)

File /anaconda/envs/py39/lib/python3.9/site-packages/t5x/partitioning.py:795, in BasePjitPartitioner.compile(self, partitioned_fn, *args)
    793 def compile(self, partitioned_fn: PjittedFnWithContext,
    794             *args) -> CompiledPartitionedCallable:
--> 795   return partitioned_fn.lower(*args).compile()

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/_src/stages.py:221, in Lowered.compile(self)
    220 def compile(self) -> Compiled:
--> 221   return Compiled(self._lowering.compile(), self.args_info,
    222                   self.out_tree, no_kwargs=self._no_kwargs)

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/interpreters/pxla.py:2346, in MeshComputation.compile(self, _allow_propagation_to_outputs, _allow_compile_replicated)
   2342 def compile(self,
   2343             _allow_propagation_to_outputs : bool = False,
   2344             _allow_compile_replicated : bool = True) -> 'MeshExecutable':
   2345   if self._executable is None:
-> 2346     self._executable = MeshExecutable.from_hlo(
   2347         self._name, self._hlo, **self.compile_args,
   2348         _allow_propagation_to_outputs=_allow_propagation_to_outputs,
   2349         _allow_compile_replicated=_allow_compile_replicated)  # type: ignore
   2350   return self._executable

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/interpreters/pxla.py:2456, in MeshExecutable.from_hlo(name, computation, mesh, global_in_avals, global_out_avals, in_axes, out_axes, spmd_lowering, tuple_args, in_is_global, auto_spmd_lowering, _allow_propagation_to_outputs, _allow_compile_replicated)
   2453 else:
   2454   with dispatch.log_elapsed_time(f"Finished XLA compilation of {name} "
   2455                                  "in {elapsed_time} sec"):
-> 2456     xla_executable = dispatch.compile_or_get_cached(backend, computation, compile_options)
   2458   if auto_spmd_lowering:
   2459     in_axes, out_axes = _get_array_mapping_from_executable(xla_executable, mesh)

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/_src/dispatch.py:664, in compile_or_get_cached(backend, computation, compile_options)
    661   ir_str = (computation if isinstance(computation, str)
    662             else computation.as_hlo_text())
    663   _dump_ir_to_file(module_name, ir_str)
--> 664 return backend_compile(backend, computation, compile_options)

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/_src/profiler.py:206, in annotate_function.<locals>.wrapper(*args, **kwargs)
    203 @wraps(func)
    204 def wrapper(*args, **kwargs):
    205   with TraceAnnotation(name, **decorator_kwargs):
--> 206     return func(*args, **kwargs)
    207   return wrapper

File /anaconda/envs/py39/lib/python3.9/site-packages/jax/_src/dispatch.py:618, in backend_compile(backend, built_c, options)
    614 @profiler.annotate_function
    615 def backend_compile(backend, built_c, options):
    616   # we use a separate function call to ensure that XLA compilation appears
    617   # separately in Python profiling results
--> 618   return backend.compile(built_c, compile_options=options)

RuntimeError: UNIMPLEMENTED: Requested AllReduceStart not implemented on GPU; replica_count: 1; partition_count: 2, group_mode: kCrossReplicaAndPartition, operand_count: 49; NCCL support: 1; first operand array element-type: BF16
  In call to configurable 'train' (<function train at 0x7fed3c31e3a0>)

**Comment by ibulu** [comment]
looks like this error has smth to do with partitioning. Not sure why setting num_partitions didn't work. It'd be good to have some examples for (multi-host) multi-gpu settings. 
Following fixed it, just in case anyone else experience this issue:

partitioning.PjitPartitioner:
  num_partitions = None
  model_parallel_submesh = (1,1,1,2)

partitioning.PjitPartitioner.logical_axis_rules = [
    ('batch', 'data'),
    ('vocab', None),
    ('embed', None),
    ('mlp', None),
    ('heads', None),
    ('kv', None),
    ('joined_kv', None),
    ('relpos_buckets', None),
    ('abspos_buckets', None),
    ('length', None),
    ('layers', None),
    ('stack', None),
    ('mlp_activations', None),
]

**Comment by adarob** [comment]
Fixed by #643
