### ISSUE TITLE
Import error with flax.optim

### ISSUE THREAD

**Issue by akku779** [google-research/t5x#717]
I'm trying to train T5X on the Winograd schema challenge. I run the training script as instructed on the tutorial but receive this error.

`ImportError: cannot import name 'optim' from 'flax' (/home/[name]/.local/lib/python3.8/site-packages/flax/__init__.py) 
`

**Comment by BioGeek** [comment]
You have installed [flax 0.6.0 which removed `flax.optim`](https://github.com/google/flax/commit/cda7a4c85bbce744e412ab82e298ddf76d4770d2).

[This pull  request](https://github.com/google-research/t5x/pull/716) removed `flax.optim` from the T5X codebase.

So either downgrade `flax` to version 0.5.3 or upgrade T5X.

**Comment by akku779** [comment]
@BioGeek 
Thanks for the solution. I am now receiving a new error. Any idea what the issue is now?

`I0820 04:45:32.290065 139785436871744 xla_bridge.py:345] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0820 04:45:32.290236 139785436871744 xla_bridge.py:345] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0820 04:45:32.290321 139785436871744 xla_bridge.py:345] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
2022-08-20 04:45:32.290673: F external/org_tensorflow/tensorflow/core/tpu/tpu_library_init_fns.inc:100] TpuEmbeddingEngine_CollateMemory not available in this library.
Fatal Python error: Aborted`

`E0820 04:45:32.347344    7488 coredump_hook.cc:365] RAW: Remote crash data gathering hook invoked.
E0820 04:45:32.347360    7488 coredump_hook.cc:411] RAW: Skipping coredump since rlimit was 0 at process start.
E0820 04:45:32.347375    7488 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0820 04:45:32.347382    7488 coredump_hook.cc:473] RAW: Sending fingerprint to remote end.
E0820 04:45:32.347393    7488 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0820 04:45:32.347427    7488 coredump_hook.cc:477] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0820 04:45:32.347431    7488 coredump_hook.cc:550] RAW: Discarding core.
E0820 04:45:32.362338    7488 process_state.cc:765] RAW: Raising signal 6 with default behavior
Aborted (core dumped)`
