### ISSUE TITLE
Error after update in train.py

### ISSUE THREAD

**Issue by peregilk** [google-research/t5x#799]
@adarob @t5-copybara

I have started getting this error:
'''
 File "../../t5x/t5x/train.py", line 254, in train
    train_iter = clu.data.TfDatasetIterator(train_iter, checkpoint=True)
TypeError: __init__() got an unexpected keyword argument 'checkpoint'
'''

I noticed this line was updated yesterday.

**Comment by elmadany** [comment]
@peregilk I'm facing the same issue. Did you solve it?

**Comment by Saisimon** [comment]
```
git clone https://github.com/google/CommonLoopUtils.git
cd CommonLoopUtils
python3 -m pip install -e .
```
I resolved this error using the above command.
